source ~/.shell/functions.sh

if [ -f ~/.shell_local_before ]; then
  source ~/.shell_local_before
fi

if [ -f ~/.bashrc_local_before ]; then
  source ~/.bashrc_local_before
fi

source ~/.bash/settings.bash

source ~/.shell/external.sh

source ~/.shell/aliases.sh

source ~/.bash/prompt.bash

source ~/.bash/plugins.bash

if [ -f ~/.shell_local_after ]; then
  source ~/.shell_local_after
fi

if [ -f ~/.bashrc_local_after ]; then
  source ~/.bashrc_local_after
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
