source ~/.shell/functions.sh

if [ -f ~/.shell_local_before ]; then
  source ~/.shell_local_before
fi

if [ -f ~/.bashrc_local_before ]; then
  source ~/.bashrc_local_before
fi

source ~/.bash/settings.bash

source ~/.shell/external.sh

source ~/.shell/aliases.sh

source ~/.bash/prompt.bash

source ~/.bash/plugins.bash

if [ -f ~/.shell_local_after ]; then
  source ~/.shell_local_after
fi

if [ -f ~/.bashrc_local_after ]; then
  source ~/.bashrc_local_after
fi
