- defaults:
    link:
        create: true
        force: true
        relink: true

- clean: ['~']

- link:
    ~/.bash:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.cliff.toml:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.scripts:
    ~/.shell:
    ~/.local/share/backgrounds: wallpapers/images
    ~/.config/bat: config/bat
    ~/.config/bottom: config/bottom
    ~/.config/conky: config/conky
    ~/.config/starship.toml: shell/plugins/starship.toml

- shell:
    - cat ~/.shell/gterminal.profiles | dconf load /org/gnome/terminal/
    - . $HOME/.bashrc
    - source $HOME/.bashrc
