- defaults:
    link:
        create: true
        force: true
        relink: true

- clean: ['~']

- shell:
    -
        command: ../.dotbot-scripts/dnf-repositories.sh
        description: Enable DNF repositories
        quiet: true
        stderr: true
        stdout: true
    -
        command: ../.dotbot-scripts/sh-installs.sh
        description: Install from shell
        quiet: true
        stderr: true
        stdout: true

- omnipkg:
    - upgrade
    - install: [
        bat,
        bottom,
        eza,
        git-delta,
        onefetch,
        screenfetch,
        tealdeer,
        zoxide
    ]

- link:
    ## bash files
    ~/.bashrc.d:
    ~/.bash-preexec.sh:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:

    ## git files
    ~/.gitconfig:
    ~/.gitignore_global:

    ## config files
    ~/.config/atuin: config/atuin
    ~/.config/bat: config/bat
    ~/.config/bottom: config/bottom
    ~/.config/git-cliff: config/git-cliff
    ~/.config/tealdeer: config/tealdeer
    ~/.config/starship.toml: config/starship.toml

- shell:
    - . $HOME/.bashrc
    - source $HOME/.bashrc
