- defaults:
    link:
        create: true
        force: true
        relink: true

- clean: ['~']

- link:
    ~/.bash:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.bat.conf:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.scripts:
    ~/.shell:
    ~/.wallpapers:

- shell:
    - . $HOME/.bashrc
    - source $HOME/.bashrc
