- defaults:
    link:
        create: true
        force: true
        relink: true

- clean: ['~']

- link:
    ~/.bash:
    ~/.bash_logout:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.scripts:
    ~/.shell:
    ~/.wallpapers:
    ~/.config/bat/config: shell/plugins/bat.conf
    ~/.config/starship.toml: shell/plugins/starship.toml

- shell:
    - cat ~/.shell/gterminal.profiles | dconf load /org/gnome/terminal/
    - . $HOME/.bashrc
    - source $HOME/.bashrc
