--==============================================================================
-- 	2022/05/23

-- 	this is for conky version 1.10.8 or newer
--
--  Based on GOTHAM theme

--  authors  : inigochoa
--  license : Distributed under the terms of GNU GPL version 3 or later

--==============================================================================

conky.config = {
	alignment = 'top_left',
	color1 = 'FFA300',
	cpu_avg_samples = 2,
	default_color = 'white',
	default_outline_color = 'green',
	default_shade_color = 'red',
	double_buffer = true,
	draw_borders = false,
	draw_graph_borders = false,
	draw_outline = false,
	draw_shades = false,
	font = 'Ubuntu:pixelsize=11',
	gap_x = 0,
	gap_y = 0,
    minimum_height = 550,
	minimum_width = 0,
	net_avg_samples = 1,
	no_buffers = true,
	override_utf8_locale = true,
	own_window = true,
	own_window_argb_value = 0,
	own_window_argb_visual = true,
	own_window_colour = '#000000',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_transparent = true,
	own_window_type = 'normal',
	total_run_times = 0,
	update_interval = 1,
	uppercase = false,
	use_spacer = 'left',
    use_xft = true,
	xftalpha = 0.1,

	template0 = [[${voffset \1}${offset \2}]],
	template1 = [[${color1}\1 ${offset 5}${color}\2]],
	template2 = [[${color1}\1 ${offset 5}${color}\2/\3]],
	template3 = [[${offset 8} · ${offset 8}]],
}

conky.text = [[
${color1}${font GE Inspira:pixelsize=120}${time %H:%M}${font}${voffset -84}${offset 10}$color${font GE Inspira:pixelsize=42}${time %d} ${voffset -15}$color${font GE Inspira:pixelsize=22}${time %B} ${time %Y}${font}${voffset 24}${font GE Inspira:pixelsize=58}${offset -162}${time %A}${font}
${template0 25 12}\
${template2 SSD $fs_free $fs_size}\
${template3}${template2 RAM $mem $memmax}\
${template3}${color1}CPU ${offset 5}$color${cpu cpu0}%\
${template3}${color1}temp ${offset 5}$color${acpitemp}°C
${template0 10 12}\
${if_up wlo1}\
${color1}${wireless_essid wlo1} ${offset 5}$color${wireless_link_qual_perc wlo1}%\
${template3}${color1}IP ${offset 5}$color${addr wlo1}\
${template3}${color1}up ${offset 5}$color${upspeed wlo1}\
${template3}${color1}down ${offset 5}$color${downspeed wlo1}
${else}\
${if_up enp3s0}\
${color1}ethernet$color\
${template3} ${color1}IP ${offset 5}$color${addr enp3s0}\
${template3}${color1}up ${offset 5}$color${upspeed enp3s0}\
${template3}${color1}down ${offset 5}$color${downspeed enp3s0}
${endif}\
${endif}\
${template0 10 12}\
${if_match "${execi 10000 which docker}" != ""}\
${color1}containers ${offset 5}$color${exec docker ps -q | wc -l}\
${template3}\
${endif}\
${color1}VPN ${offset 5}$color${if_empty ${exec cat /proc/net/route | grep tun0}}down${else}up${endif}
]]
